/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package decimalabinario;

/**
 *
 * @author Estudiantes
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingrese numero Decimal:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Signo:");

        jLabel4.setText("Exponente:");

        jLabel5.setText("Mantisa:");

        jButton1.setText("Convertir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText(",");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(74, 74, 74)
                        .addComponent(jLabel3)
                        .addGap(0, 138, Short.MAX_VALUE))
                    .addComponent(jTextField4))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(0, 33, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ConvertirBinario cb = new ConvertirBinario();
        Lista lis = new Lista();
        CalcularExponente ce = new CalcularExponente();
        int numero = Integer.parseInt(jTextField1.getText());
        int original = numero;
        String flot = jTextField5.getText();
        double decimal = 0;
        
        if(flot.length() == 4){
            decimal = Integer.parseInt(flot);
            decimal = decimal/1000.000;
        }
        if(flot.length() == 3){
            decimal = Integer.parseInt(flot);
            decimal = decimal/1000.000;
        }
        if(flot.length() == 2){
            decimal = Integer.parseInt(flot);
            decimal = decimal/100.000;
        }
        if(flot.length() == 1){
            decimal = Integer.parseInt(flot);
            decimal = decimal/10.000;
        }
        
        //Calcular el signo
        if(numero>0){
            lis.insertar(0);
            jTextField2.setText(lis.mostrarS());
        }else{
            lis.insertar(1);
            jTextField2.setText(lis.mostrarS());
        }
        
        //Calcular el exponente
        numero = ce.calcularExponente(numero,decimal);
        if(numero>=128){
            numero = numero - 128;
            lis.insertar(1);
        }else{
            lis.insertar(0);
        }
        if(numero>=64){
            numero = numero - 64;
            lis.insertar(1);
        }else{
            lis.insertar(0);
        }
        if(numero>=32){
            numero = numero - 32;
            lis.insertar(1);
        }else{
            lis.insertar(0);
        }
        if(numero>=16){
            numero = numero - 16;
            lis.insertar(1);
        }else{
            lis.insertar(0);
        }
        if(numero>=8){
            numero = numero - 8;
            lis.insertar(1);
        }else{
            lis.insertar(0);
        }
        if(numero>=4){
            numero = numero - 4;
            lis.insertar(1);
        }else{
            lis.insertar(0);
        }
        if(numero>=2){
            numero = numero - 2;
            lis.insertar(1);
        }else{
            lis.insertar(0);
        }
        if(numero>=1){
            numero = numero - 1;
            lis.insertar(1);
        }else{
            lis.insertar(0);
        }
        jTextField3.setText(lis.mostrarE());
        
        //Calcular la matiza
        if(original>0){
            original = original;
        }else{
            original = (original * (-1));
        }
        numero = original;
        if(numero>=256){
            if(numero>=128){
                numero = numero - 256;
            }
            if(numero>=128){
                numero = numero - 128;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            if(numero>=64){
                numero = numero - 64;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            if(numero>=32){
                numero = numero - 32;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            if(numero>=16){
                numero = numero - 16;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            if(numero>=8){
                numero = numero - 8;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            if(numero>=4){
                numero = numero - 4;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            if(numero>=2){
                numero = numero - 2;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            if(numero>=1){
                numero = numero - 1;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            decimal = decimal*2;
            for(int i=0; i<15; i++){
                double aux = decimal;
                decimal = decimal*2;
                int fin = (int) aux;                
                if(decimal>1.999){
                    decimal = decimal - (2);
                    i--;                    
                }
                if(fin<2){
                    lis.insertar(fin);
                }
            }
        }
        else if(numero>=128){
            if(numero>=128){
                numero = numero - 128;
            }            
            if(numero>=64){
                numero = numero - 64;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            if(numero>=32){
                numero = numero - 32;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            if(numero>=16){
                numero = numero - 16;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            if(numero>=8){
                numero = numero - 8;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            if(numero>=4){
                numero = numero - 4;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            if(numero>=2){
                numero = numero - 2;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            if(numero>=1){
                numero = numero - 1;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            decimal = decimal * 2;
            for(int i=0; i<16; i++){
                double aux = decimal;
                decimal = decimal*2;
                int fin = (int) aux;                
                if(decimal>1.999){
                    decimal = decimal - (2);
                    i--;                    
                }
                if(fin<2){
                    lis.insertar(fin);
                }
            }
        }
        else if(numero>=64){
            if(numero>=64){
                numero = numero - 64;                
            }
            if(numero>=32){
                numero = numero - 32;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            if(numero>=16){
                numero = numero - 16;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            if(numero>=8){
                numero = numero - 8;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            if(numero>=4){
                numero = numero - 4;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            if(numero>=2){
                numero = numero - 2;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            if(numero>=1){
                numero = numero - 1;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            decimal =  decimal * 2;
            for(int i=0; i<17; i++){
                double aux = decimal;
                decimal = decimal*2;
                int fin = (int) aux;                
                if(decimal>1.999){
                    decimal = decimal - (2);
                    i--;                    
                }
                if(fin<2){
                    lis.insertar(fin);
                }
            }
        }
        else if(numero>=32){
            if(numero>=32){
                numero = numero - 32;
            }
            if(numero>=16){
                numero = numero - 16;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            if(numero>=8){
                numero = numero - 8;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            if(numero>=4){
                numero = numero - 4;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            if(numero>=2){
                numero = numero - 2;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            if(numero>=1){
                numero = numero - 1;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            decimal =  decimal*2;
            for(int i=0; i<18; i++){
                double aux = decimal;
                decimal = decimal*2;
                int fin = (int) aux;                
                if(decimal>1.999){
                    decimal = decimal - (2);
                    i--;                    
                }
                if(fin<2){
                    lis.insertar(fin);
                }
            }
        }
        else if(numero>=16){
            if(numero>=16){
                numero = numero - 16;
            }
            if(numero>=8){
                numero = numero - 8;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            if(numero>=4){
                numero = numero - 4;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            if(numero>=2){
                numero = numero - 2;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            if(numero>=1){
                numero = numero - 1;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            decimal =  decimal *2;
            for(int i=0; i<19; i++){
                double aux = decimal;
                decimal = decimal*2;
                int fin = (int) aux;                
                if(decimal>1.999){
                    decimal = decimal - (2);
                    i--;                    
                }
                if(fin<2){
                    lis.insertar(fin);
                }
            }
        }
        else if(numero>=8){
            if(numero>=8){
                numero = numero - 8;
            }
            if(numero>=4){
                numero = numero - 4;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            if(numero>=2){
                numero = numero - 2;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            if(numero>=1){
                numero = numero - 1;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            decimal =  decimal*2;
            for(int i=0; i<20; i++){
                double aux = decimal;
                decimal = decimal*2;
                int fin = (int) aux;                
                if(decimal>1.999){
                    decimal = decimal - (2);
                    i--;                    
                }
                if(fin<2){
                    lis.insertar(fin);
                }
            }
        }
        else if(numero>=4){
            if(numero>=4){
                numero = numero - 4;
            }
            if(numero>=2){
                numero = numero - 2;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            if(numero>=1){
                numero = numero - 1;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            decimal =  decimal*2;
            for(int i=0; i<21; i++){
                double aux = decimal;
                decimal = decimal*2;
                int fin = (int) aux;                
                if(decimal>1.999){
                    decimal = decimal - (2);
                    i--;                    
                }
                if(fin<2){
                    lis.insertar(fin);
                }
            }
        }
        else if(numero>=2){
            if(numero>=2){
                numero = numero - 2;
            }
            if(numero>=1){
                numero = numero - 1;
                lis.insertar(1);
            }else{
                lis.insertar(0);
            }
            decimal = decimal*2;
            for(int i=0; i<22; i++){
                double aux = decimal;
                decimal = decimal*2;
                int fin = (int) aux;                
                if(decimal>1.999){
                    decimal = decimal - (2);
                    i--;                    
                }
                if(fin<2){
                    lis.insertar(fin);
                }
            }
        }
        else if(numero>=1){
            if(numero>=1){
                numero = numero - 1;
            }
            decimal = decimal*2;
            for(int i=0; i<23; i++){
                double aux = decimal;
                decimal = decimal*2;
                int fin = (int) aux;                
                if(decimal>1.999){
                    decimal = decimal - (2);
                    i--;                    
                }
                if(fin<2){
                    lis.insertar(fin);
                }
            }
        }else{
            decimal = decimal*2;
            int f = 0;
            do{
                double aux = decimal;
                decimal = decimal*2;
                int fin = (int) aux;                
                if(decimal>1.999){
                    decimal = decimal - (2);                    
                }
                f = fin;
            }while(f != 1);
            for(int i=0; i<23; i++){
                double aux = decimal;
                decimal = decimal*2;
                int fin = (int) aux;                
                if(decimal>1.999){
                    decimal = decimal - (2);
                    i--;                    
                }
                if(fin<2){
                    lis.insertar(fin);
                }
            }
        }
        jTextField4.setText(lis.mostrarM());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Principal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
